# Manual Game Entries
# Add your custom games here


# You can add more games following this format
# [[games]]
# name = "Game Name"
# exec = "command to launch"
# image = "path/to/cover.png"
# category = "category-name"
# favorite = true/false
